Rana scanner flash
CMPUT301W23T08/qrchive pull request #74
Opened 2023-03-11 17:10 UTC by sunjogthind

Build Gradle issue resolved now.
Working flash.

2023-03-11 23:00 UTC, StaticESC reviewed
Apart from the comments, LGTM

2023-03-11 23:00 UTC, jsh3lly commented on app/src/main/java/com/example/qrchive/Classes/MapModel.java
Don't commit this, this is deleted in a different PR anyway

2023-03-11 23:00 UTC, jsh3lly commented on .idea/deploymentTargetDropDown.xml
> +</project>
Don;t commit this

2023-03-11 23:21 UTC, sunjogthind commented on .idea/deploymentTargetDropDown.xml
> +</project>
Will this cause an issue?

2023-03-11 23:21 UTC, sunjogthind commented on app/src/main/java/com/example/qrchive/Classes/MapModel.java
Cool

2023-03-12 04:42 UTC, sunjogthind commented on .idea/deploymentTargetDropDown.xml
> +</project>
removed the folder

2023-03-12 04:49 UTC, sunjogthind commented on app/src/main/java/com/example/qrchive/Classes/MapModel.java
fixed -hd

2023-03-12 06:45 UTC, StaticESC requested changes
DO NOT delete the entire `.idea/` folder and then push it to Github. That means that when we try to pull origin, OUR `.idea/` folder gets deleted.

2023-03-12 18:30 UTC, closed without merging